### ISSUE TITLE
[Testing Party] Phone Number Not Validated When Adding a Business

### ISSUE THREAD

**Issue by dbleek** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#125]
Steps to recreate:

1. Go to Add a Business
2. Enter invalid input for phone number
3. Complete the rest of the form
4. Click Add Business

**Comment by vchrombie** [comment]
Thanks for opening the issue! We were able to reproduce the issue.

Kudos @dbleek! 🎉

**Comment by StephanieHou** [comment]
Added validation to phone number fields. Closing issue
