### ISSUE TITLE
[Testing Party] Sign in state not preserved

### ISSUE THREAD

**Issue by thehanimo** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#126]
Navigating back after signing in takes me back to the sign in page. Navigating forward takes me to the home page again, which shows a mismatch in sign in state.

https://user-images.githubusercontent.com/37334271/231671776-ab6ba487-7959-42c0-bb3b-56eac07a6f89.mov

**Comment by suryasdas** [comment]
Had the same issue during testing.

**Comment by vchrombie** [comment]
Thanks for opening the issue! We were able to reproduce the issue.

Kudos @thehanimo! 🎉

**Comment by StephanieHou** [comment]
Fixed backwards into login/sign up. Closing issue.
