### ISSUE TITLE
[Testing Party] General Feedback

### ISSUE THREAD

**Issue by vchrombie** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#128]
Hello everyone,

As professor suggested, I wanted to reach out to all the teams for feedback on what we've built so far. We're looking for general feedback on the user interface, functionality, and overall experience of using our software.

If you've had a chance to test our project, please share your thoughts and experiences with us. We welcome all feedback, including constructive criticism, suggestions for improvements, and positive feedback on what you liked about our project.

Feel free to comment on this issue. Your feedback will be extremely valuable in helping us make our software even better.

Thank you in advance for your feedback!

**Comment by ap2963** [comment]
Great work! 

I would suggest the landing page after login be the user's "My Account" page, as opposed to the general home page. 

Additionally, I think it would be helpful visually to have separate pages for account management (i.e. "My profile") and the user's listings (i.e. things related to businesses and neighborhoods).

**Comment by vchrombie** [comment]
Thank you for your feedback @ap2963!
