### ISSUE TITLE
[Testing Party] User2 cannot login after updating with default

### ISSUE THREAD

**Issue by EdenWuyifan** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#129]
I'm testing profile update with user2. I clicked the update button without changing anything. However, the website shows 502 Bad Gateway after clicked the button. And for some reason I could not log in anymore.

The account and password are correct and the site wasn't showing invalid credential. it just redirect to login without doing anything.
![image](https://user-images.githubusercontent.com/43869961/231866231-52791b58-e607-4950-91aa-b585cfb48121.png)
![image](https://user-images.githubusercontent.com/43869961/231866463-b2f0b6b4-0724-4a01-96ab-3343761c62e8.png)

**Comment by vchrombie** [comment]
> I'm testing profile update with user2. I clicked the update button without changing anything. However, the website shows 502 Bad Gateway after clicked the button. And for some reason I could not log in anymore.
> 
> The account and password are correct and the site wasn't showing invalid credential. it just redirect to login without doing anything.

We are really sorry about the issue. It happens sometimes because of the AWS, we are really not sure what the problem is. After waiting a couple of minutes, the site starts working fine.

We mentioned about this problem in the document as well.

> If you encounter unusual behavior with the AWS instance, we kindly ask for your patience. Please wait for a few minutes before performing any actions again.
