### ISSUE TITLE
[Testing Party] Generic Feedback

### ISSUE THREAD

**Issue by joeleu** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#130]
I absolutely love the homepage. The graphic and brief description are great, they really welcome someone to the site. The style overall is excellent and shows real promise.

The neighborhoods page with the map divided into neighborhoods is awesome, especially how you can select one and zoom in on it. Those were great design choices.

Keep up the great work!

**Comment by AlfaroukSaleh** [comment]
Thank you so much @joeleu for your kind feedback ^_^
