### ISSUE TITLE
[Testing Party] Business Details URL

### ISSUE THREAD

**Issue by joeleu** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#134]
It is tempting to use the primary key for an object as the path identifier in a URL given its inherent uniqueness but when the URL is opaque to the user it can be harder for them to find what they are looking for. Consider using something else as the path ID.

**Comment by vchrombie** [comment]
> 
It is tempting to use the primary key for an object as the path identifier in a URL given its inherent uniqueness but when the URL is opaque to the user it can be harder for them to find what they are looking for. Consider using something else as the path ID.

Thank you for opening the issue. We will take this into consideration. 😃
