### ISSUE TITLE
[TP - TEAM 2] search count mismatch

### ISSUE THREAD

**Issue by punitoff** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#138]

**Comment by punitoff** [comment]
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/54942167/231936586-d6f73a6f-1ac2-4ee9-9a3a-c08ec2d5fe75.png">

**Comment by AlfaroukSaleh** [comment]
@punitoff Wrong Repo Lol.
