### ISSUE TITLE
Cannot select the neighborhood using the dropdown

### ISSUE THREAD

**Issue by vchrombie** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#161]
Login > Profile > Add a Listing

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/25265451/233184274-5f1f9a63-bd6e-429b-97da-39d0f4ff174f.png">

Looks like the neighborhoods data is being passed but not able to load it in the frontend.

**Comment by moringspeaker** [comment]
I also noticed that and I tried to solve this today but I failed T_T

**Comment by moringspeaker** [comment]
I think I've fixed it, check my lastest push in branch develop
