### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by moringspeaker** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#175]
![image](https://user-images.githubusercontent.com/55912169/236119344-1a74ee01-eeb5-4336-a94d-b26de3ab27a0.png)
We can;'t open our neighborhood page but I believe it's a tiny bug
@StephanieHou 
@vanessasinam 
@ws2309nyu 
@AlfaroukSaleh

**Comment by vchrombie** [comment]
Hi @moringspeaker
I cannot reproduce the issue. Maybe try deleting the db file and running the migrate command, might fix the issue.

Please re-open the issue otherwise.
