### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#39]
The user after login should be able to view their profile.

- should validate if the user is logged in
- the profile should show the user details like first name, last name, and the list of their businesses if they have any
- each business should show the name, address, phone number and email contact

**Comment by vchrombie** [comment]
http://bam-env.eba-n2psxg2h.us-west-2.elasticbeanstalk.com/users/
