### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#41]
The user should be able to register using a form if they don't have an account

- form should contain the details like first name, last name, email, password
- should also have password confirmation
- check if the password matches
- check if there is an account existing with that email
- create a new account after submitting the button
- redirect to user profile

**Comment by vchrombie** [comment]
http://bam-env.eba-n2psxg2h.us-west-2.elasticbeanstalk.com/users/register/
