### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#42]
The user should be able to login to his profile.

- login should have a form with email and password fields
- should check if the user has an account
- fetch his profile and stores the session
- redirect to his profile
- should be able to logout
- should be able to register a business or view a business

**Comment by vchrombie** [comment]
http://bam-env.eba-n2psxg2h.us-west-2.elasticbeanstalk.com/users/login/
