### ISSUE TITLE
Add a business

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#44]
The user after login should be able to add a business using the add business form.

- should validate if the user is logged in
- form should contain the business fields
- create a business with the data from the fields and the user as `owner`
- redirect to viewing the business page

**Comment by vchrombie** [comment]
http://bam-env.eba-n2psxg2h.us-west-2.elasticbeanstalk.com/users/add_business/
