### ISSUE TITLE
Setting up CD

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#64]

**Comment by AlfaroukSaleh** [comment]
Add CD your main branch → your AWS production instance

**Comment by vchrombie** [comment]
The CD is setup using travis. The secrets are setup in the travis project settings.

https://github.com/gcivil-nyu-org/INET-Monday-Spring2023-Team-5/blob/develop/.travis.yml

https://app.travis-ci.com/github/gcivil-nyu-org/INET-Monday-Spring2023-Team-5
